#
#    +++++++  ++++++  +++++++  +++++++  +++++++
#    +|   ++  +|         ++    +|   ++  +|   ++
#    +++++++  ++++++     ++    +++++++  +++++++
#    +|   ++      ++     ++    +| ++    +|   ++
#    +|   ++  ++++++     ++    +|   ++  +|   ++
#
#    AstraPrison
#    Developed by Mantice
#

#
# Console Log Settings
#
logging:

  #| Allow color in console messages?
  #|
  allow-formatting: true

  #| Send debug messages to console?
  #|
  debug-mode: false