main: dev.fabled.astra.AstraPrison
name: Astra
version: ${version}
api-version: '1.20'
authors: ['Mantice']
description: The ultimate modern prison core!
website: https://astra.paracausal.dev

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false